services:
  db:
    image: postgres:15
    conainer_name: cost_db
    environment:
      POSTGRES_USER: ${COSTS_DB_USER:-admin}
      POSTGRES_PASSWORD: ${COSTS_DB_PASSWORD:-123456}
      POSTGRES_DB: ${COSTS_DB_NAME:-cost_structure_db}
    volumes:
      - COSTS_DB_Data:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${COSTS_DB_USER:-admin} -d ${COSTS_DB_NAME:-cost_structure_db}"]
      interval: 5s
      timeout: 5s
      retries: 5

  app:
    build: .
    container_name: cost_app
    depends_on:
      db:
        condition: service_healthy 
    environment:
      PORT: 3000
      DB_HOST: db 
      DB_USER: ${COSTS_DB_USER:-admin}
      DB_PASSWORD: ${COSTS_DB_PASSWORD:-123456}
      DB_NAME: ${COSTS_DB_NAME:-cost_structure_db}
      DB_PORT: 5432
      DB_DIALECT: postgres
    ports:
      - "3000:3000"

  volumes:
    MinsaCostos_DB_Data:
