services:
  db:
    image: postgres:15
    conainer_name: cost_db
    environment:
      POSTGRES_USER: ${COSTS_DB_USER:-admin}
      POSTGRES_PASSWORD: ${COSTS_DB_PASSWORD:-123456}
      POSTGRES_DB: ${COSTS_DB_NAME:-cost_structure_db}
    volumes:
      - COSTS_DB_Data:/var/lib/postgresql/data
    ports:
      - "5433:5432"

  volumes:
    COSTS_DB_Data:
